server:
  port: 8081
# Specify the DBMS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PaintMooc
    username: root
    password: 123
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
# Show or not log for each sql query
    show-sql: true
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
# Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# stripped before adding them to the entity manager)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  devtools:
      remote:
        secret: remotesecret
#Application specific

authentication:
  oauth:
    clientid: paintmooc
    secret: secret
    tokenValidityInSeconds: 3600000

messagesdk:
  alidayu:
    appkey: 23343939
    appsecret: af50665089a7319cd63503799eb555f2
